#ifndef ELECTROCOMPONENTS_GLOBAL_H
#define ELECTROCOMPONENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ELECTROCOMPONENTS_LIBRARY)
#  define ELECTROCOMPONENTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ELECTROCOMPONENTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ELECTROCOMPONENTS_GLOBAL_H
